POST http://localhost:5002/books
Content-Type: application/json

{
  "name": "test",
  "author": "test",
  "language": "english",
  "pages": 500,
  "status": "read"
}

###
GET http://localhost:5002/books/author

###
GET http://localhost:5002/books?language=english&status=read
###

DELETE http://localhost:5002/books/698226a5b30d9b6154e9ca18

###
PATCH http://localhost:5002/books/111f629677f0ad02881974bd/status
