POST http://localhost:5002/books
Content-Type: application/json

{
  "name": "test",
  "author": "test",
  "language": "test",
  "pages": 100,
  "status": "unread"
}
###
POST http://localhost:5002/books/698521793254a87f22eabfe4/reviews
Content-Type: application/json

{"rating":5,"comment":"Niceee!"}

###
GET http://localhost:5002/books

###
GET http://localhost:5002/books?language=english&status=read
###

DELETE http://localhost:5002/books/6983bf021a8fa6bd24059d19

###
PATCH http://localhost:5002/books/697f488607ef490af2c1e2f5/status
