POST http://localhost:5002/books
Content-Type: application/json

{
  "title": "Great Expectations",
  "author": "Charles Dickens",
  "pages": 500,
  "language": "English"
}

###
GET http://localhost:5002/books
