POST http://localhost:5002/books
Content-Type: application/json

{
  "name": "test",
  "author": "test",
  "language": "English",
  "pages": 500,
  "status": "unread"
}

###
GET http://localhost:5002/books
